### ISSUE TITLE
Make fails on linux (ubuntu 10.04)

### ISSUE THREAD

**Issue by boxerab** [JakSprats/Alchemy-Database#2]
Hi Russ,

Here are the errors:

make[2]: Entering directory `/home/aaron/src/Redisql/lua-5.1.4/src'
gcc -O2 -Wall    -c -o lua.o lua.c
gcc -o lua  lua.o liblua.a -lm
liblua.a(loadlib.o): In function`ll_loadfunc':
loadlib.c:(.text+0x8d8): undefined reference to `dlsym'
loadlib.c:(.text+0x931): undefined reference to`dlopen'
loadlib.c:(.text+0x949): undefined reference to `dlerror'
loadlib.c:(.text+0x960): undefined reference to`dlerror'
liblua.a(loadlib.o): In function `gctm':
loadlib.c:(.text+0xe9c): undefined reference to`dlclose'
collect2: ld returned 1 exit status
make[2]: **\* [lua] Error 1
make[2]: Leaving directory `/home/aaron/src/Redisql/lua-5.1.4/src'
make[1]: *** [generic] Error 2
make[1]: Leaving directory`/home/aaron/src/Redisql/lua-5.1.4/src'
make: **\* [generic] Error 2

Thanks,
Aaron

**Comment by JakSprats** [comment]
Hi Aaron,

I havent seen these exact errors, but I think
"sudo apt-get install readline"
is needed for lua to compile

This error is in lua, not in my code or redis code ...

maybe libdb or lidbdb-devel are needed

if all else fails adding "-ldl" into lua's makefile in the link part should do the trick

try that if it doesnt work, i will download a Ubuntu 10.04 iso, make a VM and try it out
- Jak (Russ)

**Comment by boxerab** [comment]
thanks, all I needed was:

sudo apt-get install libreadline-dev

now building.
