### ISSUE TITLE
在CentOS上安装，然后运行没有反应

### ISSUE THREAD

**Issue by wangyujingGH** [JakSprats/Alchemy-Database#6]
启动之后没有任何反应。是什么问题？
![11](https://cloud.githubusercontent.com/assets/14920006/12315147/e5b369d0-bab2-11e5-9a4b-f3bc3ba6167e.png)

**Comment by JakSprats** [comment]
Translation to english
"启动之后没有任何反应。是什么问题？" -> After starting no response. What is the problem?

Any additional information?

**Comment by wangyujingGH** [comment]
After the steps to install, everything is ok, there is no errors. So I input "./alchemy-server ../redis.conf", the response is like the picture.
![1](https://cloud.githubusercontent.com/assets/14920006/12348066/b876a396-bb9e-11e5-938d-0837f1d67b7e.png)
So I add the 'vm.overcommit_memory = 1' to /etc/sysctl.conf, then reboot.
When I setup the server again through "./alchemy-server ../redis.conf",  there is no response on console, and inputing "./alchemy-cli creat table....", there is no responses either, like the picture. 
![111](https://cloud.githubusercontent.com/assets/14920006/12348173/b006f6ce-bb9f-11e5-9b77-ea33f5f4700a.png)

I don't know why.

**Comment by JakSprats** [comment]
You need to use 2 different terminal windows.
In terminal 1, type: "./alchemy-server ../redis.conf" to start the server
In terminal 2, type: "./alchemy-cli XXXXX" to run a client command

**Comment by wangyujingGH** [comment]
sucess. thanks.
In addition, I want to ask you a question, when you desige the AlchemyDB, do you consider the relationship between the tables? Can it support the jion operation?

**Comment by JakSprats** [comment]
AlchemyDB supports some joins, but not all joins, check the documentation, it is all explained there
